roottoplate/composter/urls.py
from django.urls import path

from composter import views

app_name = 'composter'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('composter/', views.composter, name='composter'),
    path('input-entry/', views.InputFormView.as_view(), name='input_entry'),
    path('temp-entry/', views.temp_entry, name='temp_entry'),
    path('output-entry/', views.output_entry, name="output_entry"),
    path('restaurants/', views.restaurant_request_form, name='restaurant_form'),
    path('collect-request/<int:request_id>', views.collect_request, name="collect_request"),
    # admin only urls
    path('simple-admin/', views.simple_admin, name='simple_admin'),

]

roottoplate/roottoplate/urls.py
from django.contrib import admin
from composter import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('composter/', include('composter.urls')),
]

roottoplate/composter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator, MinLengthValidator


class InputType(models.Model):
    NAME_MAX_LENGTH = 128
    RATIO_DECIMAL_PLACES = 2
    RATIO_MAX_DIGITS = 5
    NITROGEN_DECIMAL_PLACES = 2
    NITROGEN_MAX_DIGITS = 5
    MOISTURE_DECIMAL_PLACES = 2
    MOISTURE_MAX_DIGITS = 5

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True, validators=[MinLengthValidator(2)],
                            primary_key=True)
    CNRatio = models.DecimalField(decimal_places=RATIO_DECIMAL_PLACES, max_digits=RATIO_MAX_DIGITS,
                                  validators=[MinValueValidator(1)])
    nitrogenPercent = models.DecimalField(decimal_places=NITROGEN_DECIMAL_PLACES, max_digits=NITROGEN_MAX_DIGITS,
                                          validators=[MinValueValidator(1)])
    moisturePercent = models.DecimalField(decimal_places=MOISTURE_DECIMAL_PLACES, max_digits=MOISTURE_MAX_DIGITS,
                                          validators=[MinValueValidator(1)])

    def __str__(self):
        return self.name


class InputEntry(models.Model):
    NOTES_MAX_LENGTH = 2048

    entryID = models.AutoField(primary_key=True)
    entryTime = models.DateTimeField()
    notes = models.CharField(max_length=NOTES_MAX_LENGTH, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Input entries'

    def __str__(self):
        return str(self.entryID)


class Input(models.Model):
    #  Facilitates the many to many relationship between input entries and input types
    INPUT_DECIMAL_PLACES = 2
    INPUT_MAX_DIGITS = 5

    inputEntry = models.ForeignKey(InputEntry, on_delete=models.CASCADE)
    inputType = models.ForeignKey(InputType, on_delete=models.CASCADE)
    inputAmount = models.DecimalField(decimal_places=INPUT_DECIMAL_PLACES, max_digits=INPUT_MAX_DIGITS,
                                      validators=[MinValueValidator(0)])


class TemperatureEntry(models.Model):
    NOTES_MAX_LENGTH = 2048
    TEMP_DECIMAL_PLACES = 2
    TEMP_MAX_DIGITS = 5

    entryID = models.AutoField(primary_key=True)
    entryTime = models.DateTimeField()
    probe1 = models.DecimalField(decimal_places=TEMP_DECIMAL_PLACES, max_digits=TEMP_MAX_DIGITS,
                                 validators=[MinValueValidator(-40), MaxValueValidator(150)])
    probe2 = models.DecimalField(decimal_places=TEMP_DECIMAL_PLACES, max_digits=TEMP_MAX_DIGITS,
                                 validators=[MinValueValidator(-40), MaxValueValidator(150)])
    probe3 = models.DecimalField(decimal_places=TEMP_DECIMAL_PLACES, max_digits=TEMP_MAX_DIGITS,
                                 validators=[MinValueValidator(-40), MaxValueValidator(150)])
    probe4 = models.DecimalField(decimal_places=TEMP_DECIMAL_PLACES, max_digits=TEMP_MAX_DIGITS,
                                 validators=[MinValueValidator(-40), MaxValueValidator(150)])
    notes = models.CharField(max_length=NOTES_MAX_LENGTH, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name_plural = 'Temperature entries'

    def __str__(self):
        return str(self.entryID)


class RestaurantRequest(models.Model):
    NAME_MAX_LENGTH = 128
    ADDRESS_MAX_LENGTH = 1024
    EMAIL_MAX_LENGTH = 128
    NOTES_MAX_LENGTH = 20048

    requestID = models.AutoField(primary_key=True)
    name = models.CharField(max_length=NAME_MAX_LENGTH)
    address = models.CharField(max_length=ADDRESS_MAX_LENGTH)
    dateRequested = models.DateTimeField()
    deadlineDate = models.DateTimeField()
    email = models.CharField(max_length=EMAIL_MAX_LENGTH)
    phoneNumber = models.CharField(null=True, max_length=13)
    notes = models.CharField(max_length=NOTES_MAX_LENGTH, null=True, blank=True)
    numberOfBags = models.IntegerField(null=True)
    collected = models.BooleanField(default=False)

    def __str__(self):
        return str(self.requestID)


class Output(models.Model):
    NOTES_MAX_LENGTH = 2048
    OUTPUT_DECIMAL_PLACES = 2
    OUTPUT_MAX_DIGITS = 5

    outputID = models.AutoField(primary_key=True)
    amount = models.DecimalField(decimal_places=OUTPUT_DECIMAL_PLACES, max_digits=OUTPUT_MAX_DIGITS)
    time = models.DateTimeField()
    notes = models.CharField(max_length=NOTES_MAX_LENGTH, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.outputID)


class EnergyUsage(models.Model):
    #  Model for meter readings, used for homepage graph calculations
    entryID = models.AutoField(primary_key=True)
    date = models.DateField()
    gas = models.IntegerField()
    electricity = models.IntegerField()

roottoplate/composter/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect
from django.views.generic import TemplateView
from composter.forms import InputEntryForm, InputFormSet, TempEntryForm, OutputForm, EnergyForm
from composter.forms import RestaurantForm, UserForm, InputTypeForm, ChangePasswordForm
from composter.models import InputType, Input, InputEntry, TemperatureEntry, RestaurantRequest
from django.utils import timezone
from composter.signals import GraphState


def index(request):
    state = GraphState()
    context = {'typeNames': state.typeNames, 'typePercentages': state.typePercentages,
               'tempEntries': state.tempEntries, 'tempTimes': state.tempTimes, 'tempTimesInt': state.tempTimesInt,
               'cMonth': state.cMonth, 'cYear': state.cYear, 'notEnoughEnergyInfo': state.notEnoughEnergyInfo}
    return render(request, "composter/index.html", context)


def about(request):
    return render(request, "composter/about.html")


def composter(request):
    context = {}
    last_five_entries = InputEntry.objects.all().order_by('-entryTime').values()[:5]

    # get time the composter was last fed
    if last_five_entries:
        compost_last_fed = last_five_entries[0].get('entryTime')
        compost_last_fed_js = compost_last_fed.strftime("%Y-%m-%dT%H:%M:%SZ")
        context = {'compost_last_fed': compost_last_fed, 'compost_last_fed_js': compost_last_fed_js}

        if request.user.is_staff:
            for entry in last_five_entries:
                entry['username'] = User.objects.get(id=entry['user_id']).username
                inputs = Input.objects.filter(inputEntry=entry['entryID']).values()
                entry['inputs'] = [{'type': i.get('inputType_id'), 'amount': i.get('inputAmount')} for i in inputs]
            context['last_five_entries'] = last_five_entries

    return render(request, "composter/composter.html", context)


@csrf_protect
def user_login(request):
    if request.user.is_authenticated:
        messages.error(request, "You are already logged in.")
        return redirect(reverse('index'))
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('index'))
            else:
                return HttpResponse("Your account is disabled")
        else:
            messages.error(request, "Invalid login details.")

    return render(request, 'composter/login.html')


@login_required(login_url='/composter/login/')
def user_logout(request):
    logout(request)
    return redirect(reverse('index'))


def calculate_mixture_sums(cur_inputs):
    sumN = sum([i['amount'] * i['nitrogen'] * i['moisture'] for i in cur_inputs])
    for i in cur_inputs:
        i['carbon'] = i['nitrogen'] * i['CNRatio']
    sumC = sum([i['amount'] * i['carbon'] * i['moisture'] for i in cur_inputs])
    return sumC, sumN


def calculate_recommended_addition(rec_input, sumC, sumN):
    cn = 27  # ideal carbon nitrogen ratio
    nitrogen, moisture = float(rec_input.nitrogenPercent), 100 - float(rec_input.moisturePercent)
    carbon = float(rec_input.nitrogenPercent * rec_input.CNRatio)
    return (cn * sumN - sumC) / (carbon * moisture - nitrogen * moisture * cn)


class InputFormView(TemplateView):
    template_name = "composter/compost_form.html"

    @method_decorator(login_required(login_url='/composter/login/'))
    def get(self, *args, **kwargs):
        context = {'input_formset': InputFormSet, 'entry_form': InputEntryForm()}
        return self.render_to_response(context)

    @method_decorator(login_required(login_url='/composter/login/'))
    def post(self, request, *args, **kwargs):
        user = User.objects.get(username=self.request.user.username)

        entry_form = InputEntryForm(self.request.POST)
        input_formset = InputFormSet(self.request.POST)
        context = {}

        if 'get_advice' in self.request.POST and input_formset.is_valid():
            cur_inputs = []
            # get the inputs without saving the form
            for input in input_formset:
                input = input.save(commit=False)
                cur_inputs.append({'amount': float(input.inputAmount),
                                   'nitrogen': float(input.inputType.nitrogenPercent),
                                   'moisture': 100 - float(input.inputType.moisturePercent),
                                   'CNRatio': float(input.inputType.CNRatio)})
            # get the total carbon and nitrogen in the mixture
            sumC, sumN = calculate_mixture_sums(cur_inputs)

            # if the ratio is too big then add more green
            if sumC / sumN > 35:
                rec_input = InputType.objects.get(name='Food waste')
                rec_input_amount = round(calculate_recommended_addition(rec_input, sumC, sumN), 1)
                advice = f"The carbon-nitrogen ratio of this mixture is too high. Recommended addition: roughly {rec_input_amount} of green material. "  # noqa:E501
            # if the ratio is too small then add more brown
            elif sumC / sumN < 20:
                rec_input = InputType.objects.get(name='Wood')
                rec_input_amount = round(calculate_recommended_addition(rec_input, sumC, sumN), 1)
                advice = f"The carbon-nitrogen ratio of this mixture is too low. Recommended addition: roughly {rec_input_amount} of brown material. "  # noqa:E501
            # the ratio is ready to submit
            else:
                advice = "The carbon-nitrogen ratio is within the recommended range. "

            tempEntries = TemperatureEntry.objects.all().order_by('-entryTime').values()
            tempMin = min(tempEntries[0].get('probe2'), tempEntries[0].get('probe3'))
            tempMax = max(tempEntries[0].get('probe2'), tempEntries[0].get('probe3'))

            if tempMax > 65:
                advice += "The temperature of the composter is above 65 at probe 2 or 3: bacterial digestion process may be destroyed. " \
                          "\nPlease add more brown material than normally recommended"  # noqa:E501
            if tempMin < 55:
                advice += "The temperature of the composter is below 55 at probe 2 or 3: more heat is needed to cook out pathogens" \
                          "\nPlease add more green material than normally recommended"  # noqa:E501
            context['advice'] = advice

        # form is submitted, process as normal
        elif entry_form.is_valid() and input_formset.is_valid():
            entry = entry_form.save(commit=False)
            entry.user = user
            entry.save()
            for inputs in input_formset:
                input = inputs.save(commit=False)
                input.inputEntry = entry
                input.save()
            return redirect(reverse('composter:composter'))
        # otherwise, show errors
        else:
            print(entry_form.errors)
            for inputs in input_formset:
                print(inputs.errors)

        context['input_formset'] = input_formset
        context['entry_form'] = entry_form
        return render(request, self.template_name, context)


@login_required(login_url='/composter/login/')
def temp_entry(request):
    user = User.objects.get(username=request.user.username)
    if request.method == 'POST':
        temp_form = TempEntryForm(request.POST)
        if temp_form.is_valid():
            temperature = temp_form.save(commit=False)
            temperature.user = user
            temperature.save()
            return redirect(reverse('composter:composter'))
        else:
            print(temp_form.errors)

    else:
        temp_form = TempEntryForm()
    return render(request, 'composter/temperature_form.html', {'temperature_form': temp_form})


@login_required(login_url='/composter/login/')
def output_entry(request):
    user = User.objects.get(username=request.user.username)
    if request.method == 'POST':
        output_form = OutputForm(request.POST)
        if output_form.is_valid():
            output = output_form.save(commit=False)
            output.user = user
            output.save()
            return redirect(reverse('composter:composter'))
        else:
            print(output_form.errors)
    else:
        output_form = OutputForm()
    return render(request, 'composter/compost_output_form.html', {'output_form': output_form})


def restaurant_request_form(request):
    if request.user.is_authenticated:
        restaurant_notifs = RestaurantRequest.objects.all()
        return render(request, 'composter/restaurant_notifs.html', {'restaurant_notifs': restaurant_notifs})
    else:
        if request.method == "POST":
            restaurant_form = RestaurantForm(request.POST)
            if restaurant_form.is_valid():
                restaurant_req = restaurant_form.save(commit=False)
                restaurant_req.dateRequested = timezone.now()
                restaurant_req.save()
                return redirect(reverse('composter:index'))
            else:
                print(restaurant_form.errors)

        else:
            restaurant_form = RestaurantForm()
        return render(request, 'composter/restaurant_form.html', {'restaurant_form': restaurant_form})


@login_required(login_url='/composter/')
def collect_request(request, request_id):
    req = RestaurantRequest.objects.get(requestID=request_id)
    req.collected = True
    req.save()
    return redirect('composter:restaurant_form')

roottoplate/templates/composter/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<head>
    <title>Root2Plate</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}">
    <link rel="icon" type="image/png" sizes="32x32" href={% static 'images/favicon.ico' %}>
</head>
<div class="grad-base">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-light bg-white static-top py-lg-0">
        <a class="navbar-brand" href="{% url 'composter:index' %}"><img src="{% static 'images/image.png' %}"
                                                                        width="170"
                                                                        height="100"
                                                                        alt=""></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto ">
                <li class="nav-item">
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'composter:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'composter:composter' %}">Composter</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'composter:restaurant_form' %}">Food Collection</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'composter:about' %}">About Us</a>
                </li>
                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'composter:simple_admin' %}">Admin Dashboard</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" style="color: rgb(224,31,29)" href="{% url 'composter:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'composter:login' %}" style="color:#B8BF0D;">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="col d-flex justify-content-center">
        <div class="container">
            {% block content_block %}
            {% endblock %}
        </div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-10 mb-3">
                    <div class="container-fluid">
                        <h4>Young Enterprise Scotland</h4>
                        <p class="text-light">
                            <span style="color: #B8BF0D">Our Vision </span> is for Scotland to be a place where all
                            young people are given the opportunity to
                            have a rewarding future in work and life - no matter where they start their journey.
                            <br>
                            <span style="color: #B8BF0D">Our Mission</span> is to inspire and equip young people,
                            irrespective of their background, to
                            learn,
                            develop and reach their full potential through enterprise and financial education.s
                            <br>
                            <span style="color: #B8BF0D">In Everything</span> that we do, we will work with the
                            following values: Integrity, Enthusiasm,
                            Creativity & Collaboration.
                        </p>
                    </div>
                    <p class="text-light">Make a donation today and help support Enterprise for All.<a
                            href="https://www.paypal.com/donate/?hosted_button_id=NHJ94KRT45X9J"
                            style="color: #B8BF0D;padding-left: 15px">Donate Now</a></p>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 ">
                    <div class="container-fluid ">
                        <h4 class="mb-1 text-light">Contact Us</h4>
                        <table class="table">
                            <caption></caption>
                            <tbody>
                            <tr>
                                <td>
                                    <a href="https://yes.org.uk/index.php">
                                        <em></em>Website</a></td>
                            </tr>
                            <tr>

                                <td><a href="tel:4401414067722">
                                    <em></em>Phone Number</a></td>
                            </tr>
                            <tr>
                                <td><a href="https://tinyurl.com/yc24up4v">
                                    <em></em>Map</a></td>
                            </tr>
                            <tr>
                                <td><a href="mailto:admin@yes.org.uk">
                                    <em></em>Email Us</a></td>
                            </tr>

                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 mb-4 ">
                    <div class="container-fluid ">
                        <h4 class="mb-1 text-light">Connect with Us</h4>
                        <table class="table" style="border-color: white;">
                            <caption></caption>
                            <tbody>
                            <tr>
                                <td>
                                    <a href="https://www.facebook.com/YoungEnterpriseScotland/">
                                        <em class="bi bi-facebook text-light" style="padding-right: 10px"></em>Facebook</a>
                                </td>
                            </tr>
                            <tr>

                                <td><a href="https://www.instagram.com/yescotland/">
                                    <em class="bi bi-instagram text-light"
                                        style="padding-right: 10px"></em>Instagram</a>
                                </td>
                            </tr>
                            <tr>
                                <td><a href="https://twitter.com/YE_Scotland">
                                    <em class="bi bi-twitter text-light"
                                        style="padding-right: 10px"></em>Twitter</a></td>
                            </tr>
                            <tr>
                                <td><a href="https://www.linkedin.com/company/young-enterprise-scotland">
                                    <em class="bi bi-linkedin text-light" style="padding-right: 10px"></em>LinkedIn</a>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>
</html>

roottoplate/templates/composter/compost_output_form.html
<!DOCTYPE html>
{% extends 'composter/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<title>Output Form</title>
{% block content_block %}
    <h1 class="card-title container text-center mb-4">Composter Output Form</h1>
    <form method="post" class="container justify-content-center"
          enctype="multipart/form-data" action="{% url 'composter:output_entry' %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div class="card w-75">
            <div class="card-body">
                {{ output_form.time.errors }}
                {{ output_form.time|as_crispy_field }}

                {{ output_form.amount.errors }}
                {{ output_form.amount|as_crispy_field }}

                {{ output_form.notes.errors }}
                {{ output_form.notes|as_crispy_field }}
                <br>
                <button type="submit" value="Post" class="btn btn-success">Submit data</button>
                <!--old button<input type="submit" name="submit" value="Post"> -->
            </div>
        </div>
    </form>
{% endblock %}

roottoplate/templates/composter/composter.html
<!DOCTYPE html>
<title>Composter</title>
{% extends 'composter/base.html' %}
{% load static %}
{% block content_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/composter.css' %}">
    <h1 class="container text-center mb-4" id="headline">Time to Next Feed</h1>
    <script src="{% static 'javascript/composter.js' %}"></script>
    <div class="card w-80 text-center mb-3">
        <div class="container text-center">
            <canvas id="canvas" width="500" height="500"></canvas>
            <h4 id="composter_last_fed" jsvalue="{{ compost_last_fed_js }}">Composter last
                fed on {{ compost_last_fed }}</h4>
            <div id="countdown">
                <div style="position: center; font-size: 20px;">
                    <ul>
                        <hi><span id="days"> </span> Days</hi>
                        <hi><span id="hours"></span> Hours</hi>
                        <hi><span id="minutes"></span> Minutes</hi>
                        <hi><span id="seconds"></span> Seconds</hi>
                    </ul>
                </div>
                <div class="message">
                    <div id="content">
                        <!--this is to stop the count down-->
                    </div>
                </div>
            </div>
            {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'composter:output_entry' %}" role="button">Output Form</a>
                <a class="btn btn-primary" href="{% url 'composter:input_entry' %}" role="button">Input Form</a>
                <a class="btn btn-primary" href="{% url 'composter:temp_entry' %}" role="button">Temperature Form</a>
            {% endif %}
            {% if user.is_staff %}
                <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample"
                   role="button" aria-expanded="false" aria-controls="collapseExample">
                    Show Logs</a>
                </div>
                </div>
                <div class="collapse" id="collapseExample">
                    <div class="card card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Entry Time</th>
                                    <th scope="col">Username</th>
                                    <th scope="col">Input Amount and Type</th>
                                    <th scope="col">Notes</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for entry in last_five_entries %}
                                    <tr>
                                    <th scope="row">{{ forloop.counter }}</th>
                                    <td>{{ entry.entryTime }}</td>
                                    <td>{{ entry.username }}</td>
                                    <td><p>
                                        {% if entry.inputs %}
                                            {% for input in entry.inputs %}
                                                {{ input.amount }}({{ input.type }})
                                                {% if not forloop.last %},{% endif %}
                                            {% endfor %}
                                        {% else %}
                                            Nothing added
                                        {% endif %}
                                    </p></td>
                                    <td>{% if entry.notes %}
                                        {{ entry.notes }}
                                    {% else %}
                                        No notes
                                    {% endif %}</td>
                                {% endfor %}
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            {% endif %}
{% endblock %}

roottoplate/templates/composter/temperature_form.html
<!DOCTYPE html>
{% extends 'composter/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<title>Temperature Form</title>
{% block content_block %}
    <h1 class="card-title container text-center mb-4">Temperature Form</h1>
    <form method="post" class="container justify-content-center"
          enctype="multipart/form-data" action="{% url 'composter:temp_entry' %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div class="card w-75">
            <div class="card-body">
                {{ temperature_form.entryTime.errors }}
                {{ temperature_form.entryTime|as_crispy_field }}

                {{ temperature_form.probe1.errors }}
                {{ temperature_form.probe1|as_crispy_field }}

                {{ temperature_form.probe2.errors }}
                {{ temperature_form.probe2|as_crispy_field }}

                {{ temperature_form.probe3.errors }}
                {{ temperature_form.probe3|as_crispy_field }}

                {{ temperature_form.probe4.errors }}
                {{ temperature_form.probe4|as_crispy_field }}

                {{ temperature_form.notes.errors }}
                {{ temperature_form.notes|as_crispy_field }}
                <div class="mb-4"></div>
                <button type="submit" value="Post" class="btn btn-success">Submit Data</button>
                <!--<input type="submit" name="submit" value="Post">-->
            </div>
        </div>

    </form>
{% endblock %}